### PR TITLE
Add idea for scaffold generation

### PR DESCRIPTION
**Pull request by joefiorini**
This is something I think would help new people out tremendously, as getting started is one of the hardest parts currently. What do you think?

### CODE REVIEW

**Comment by evancz** [comment]
Do you mind adding a "idea by @joefiorini" so people know who to get in contact with to follow up?

**Comment by evancz** [comment]
Blah, I shouldn't be such a grump. I don't really know enough about this project to give advice, and I _feel_ like I'm taking responsibility for it by listing it here. I think my feelings are wrong, so I am rejecting them :)

Thanks for the suggestion!

**Comment by joefiorini** [comment]
Thanks for pulling this in. I should have done a more detailed proposal on the elm-discuss before opening a PR here. I'll do that soon and we'll see what people think. Sound good?

**Comment by evancz** [comment]
Yeah, that'd be awesome!

I think it's okay to do PRs, I'm trying to get over fear of losing control of things. This whole repo may be better as a wiki!

**Pull request merged**
